# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - monapp2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c58f6706a21243e09473aaae942773f7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_eb513620109d455aaee25189c6ee9953 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c58f6706a21243e09473aaae942773f7 }}/imagedocker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'monapp2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_73209c0e269246b1b10abc2dcfa3b70c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c58f6706a21243e09473aaae942773f7 }}/imagedocker:${{ github.sha }}'